project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  page-footer: "@Data Analitik (2023) | UPN Veteran Yogyakarta" 
  back-to-top-navigation: true
  title: "Modul Data Analitik (R)"
  navbar:
    right: 
      - icon: github
        href: https://github.com/AktUPNYK/Project-DA
    background: dark
    search: true
  
    
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Pengantar"
        contents:
          - pengantar.qmd
          
      - section: "Topik Pembahasan"
        contents:
          - index.qmd
          - datapreparation.qmd
          - datatidy.qmd
          - datatransform.qmd
          - visualisasi.qmd
          - modelling.qmd
          - communicate.qmd
          
      - section: "Topik Lain"
        contents:
          - lain-lain.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual





